version: 2
updates:
  - package-ecosystem: "regex"
    directories:
      - "/faults"
    schedule:
      interval: "daily"
    target-branch: "v3.8.x"
    regex-managers:
      - file-match: ["(^|/)faults/.*/fault\\.ya?ml$"]
        match-strings:
          - "image:\\s+\"(?<depName>litmuschaos\\.docker\\.scarf\\.sh/litmuschaos/[^\"]+):(?<currentValue>[^\"]+)\""
        datasource-template: "docker"
        versioning-template: "docker"
